CC=g++
LIB= -lpthread
all:conditionSolution semaphoreSolution

conditionSolution:conditionSolution.cpp
	$(CC) -o $@ $< $(LIB)
	
semaphoreSolution:semaphoreSolution.cpp
	$(CC) -o $@ $< $(LIB)
	